# Rasa Configuration for ArogyaAI
# Language and pipeline configuration

language: en

pipeline:
  # WhitespaceTokenizer - splits text on whitespace
- name: WhitespaceTokenizer

  # RegexFeaturizer - creates features for regular expressions
- name: RegexFeaturizer

  # LexicalSyntacticFeaturizer - creates lexical and syntactic features
- name: LexicalSyntacticFeaturizer

  # CountVectorsFeaturizer - creates bag-of-words representation
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

  # DIETClassifier for intent classification and entity extraction
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  model_confidence: softmax

  # EntitySynonymMapper - maps synonymous entity values
- name: EntitySynonymMapper

  # ResponseSelector for responses
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true

  # FallbackClassifier for handling low confidence predictions
- name: FallbackClassifier
  threshold: 0.3
  ambiguity_threshold: 0.1

# Policies for dialogue management
policies:
  # MemoizationPolicy - remembers exact conversation patterns
- name: MemoizationPolicy

  # RulePolicy - handles rules defined in rules.yml
- name: RulePolicy

  # TEDPolicy - main policy for story-based dialogues  
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20250927-235931-stubborn-layout
